import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { cpSync } from "fs";
import { existsSync, mkdirSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// 디버깅 로그 추가
console.log("Current working directory:", process.cwd());
console.log("Expected entry point path:", "./src/main.ts");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['./src/main.ts'],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"webm-duration-fix",
		...builtins],
	format: "cjs",
	target: "node14", // Node.js 환경을 명시적으로 타겟
	platform: "node", // Node.js 환경에서 번들링
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "./dist/main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	// // ✅ webm-duration-fix 디렉토리 복사
	// const src = "node_modules/webm-duration-fix";
	// const dest = "dist/node_modules/webm-duration-fix";

	// if (!existsSync("dist/node_modules")) {
	// 	mkdirSync("dist/node_modules", { recursive: true });
	// }

	// cpSync(src, dest, { recursive: true });
	// console.log("✅ webm-duration-fix copied to dist/node_modules");	
	process.exit(0);
} else {
	await context.watch();
}